# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c66c192d1f31ef4093f09a0086f0bd9fec30e2a6d8290c830f6ff9ef1f80b19966716224352281d0866983e5502e82a4dcd139f3b168b86e2a5ce0a20fd94b1d

test:
  secret_key_base: 3e78839bc65be321cb0cb11a4d301fe23f50fd1aafec760a6275ff3e684afe038b6aa20a65ebe35175c7e1e67ee1dcd16cf5116b20b19515b41af9faedbd1556

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
